eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user.name: admin
      user.password: 123456
management:
  security:
    enabled: false
server:
  port: 5000
logging:
  file: "logs/boot-admin-sample.log"
spring:
  application:
    name: service-admin
  boot:
    admin:
      routes:
        endpoints: env, metrics, trace, dump, jolokia, info, configprops, activiti, logfile, refresh, flyway, liquibase, loggers
      turbine:
        clusters: default
        location: service-turbine
security:
  user:
    name: admin
    password: 123456