server:
  port: 5000
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
      #serviceId: hiapi-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
  #prefix: /v1
eureka:
  client:
    service-url:
      defalutZone: http://peer1:8761/eureka/
#ribbon:
#  eureka:
#    enabled: false
#hiapi-client:
#  ribbon:
#    listOfServers: http://localhost:8762,http://localhost:8763