spring:
  application:
    name: eureka-ribbon-client
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
logging:
  file: "logs/eureka-ribbon-client.log"
management:
  security:
    enabled: false