spring:
  application:
    name: service-hi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8762
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      client-id: service-hi
      client-secret: 123456
      access-token-uri: http://localhost:5000/uaa/oauth/token
      authorized-grant-types: client_credentials,password
      scope: server