server:
  port: 8769
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fateravel/springcloudconfig.git
          search-paths:
          username: fateravel
          password:
      label: master
#        native:
#          search-locations: classpath:/shared
#  profiles:
#    active: native
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/